import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:image_picker/image_picker.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:excel/excel.dart' hide Border;
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_typography.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/utils/qr_type_detector.dart';
import '../../core/widgets/glass_card.dart';
import '../../core/widgets/type_badge.dart';

class BatchScanScreen extends StatefulWidget {
  const BatchScanScreen({super.key});
  @override
  State<BatchScanScreen> createState() => _BatchScanScreenState();
}

class _BatchScanScreenState extends State<BatchScanScreen> {
  final List<_BatchItem> _items = [];
  String? _lastCode;
  DateTime _lastScanTime = DateTime.now();
  late final MobileScannerController _scanCtrl;

  @override
  void initState() {
    super.initState();
    _scanCtrl = MobileScannerController(
      detectionSpeed: DetectionSpeed.normal,
      torchEnabled: false,
    );
  }

  @override
  void dispose() {
    _scanCtrl.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) {
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null) return;

    final now = DateTime.now();
    if (raw == _lastCode && now.difference(_lastScanTime).inMilliseconds < 1500) return;

    _lastCode = raw;
    _lastScanTime = now;
    HapticFeedback.mediumImpact();

    setState(() {
      _items.insert(0, _BatchItem(raw: raw, type: detectQRType(raw), time: now));
    });
  }

  void _pickFromGallery() async {
    final picker = ImagePicker();
    final image = await picker.pickImage(source: ImageSource.gallery);
    if (image == null) return;

    try {
      final result = await _scanCtrl.analyzeImage(image.path);
      if (result != null && result.barcodes.isNotEmpty) {
        for (final barcode in result.barcodes) {
          final raw = barcode.rawValue;
          if (raw != null && raw.isNotEmpty) {
            HapticFeedback.mediumImpact();
            setState(() {
              _items.insert(0, _BatchItem(raw: raw, type: detectQRType(raw), time: DateTime.now()));
            });
          }
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Text('No QR code found in image'),
              backgroundColor: AppColors.bgElevated,
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  Future<void> _exportPdf() async {
    if (_items.isEmpty) return;
    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (ctx) => [
          pw.Header(
            text: 'Cipher — Batch Scan Report',
            level: 0,
            textStyle: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Text('${_items.length} items scanned', style: const pw.TextStyle(fontSize: 12)),
          pw.SizedBox(height: 16),
          pw.Table.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            cellStyle: const pw.TextStyle(fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellPadding: const pw.EdgeInsets.all(6),
            headers: ['#', 'Type', 'Data', 'Time'],
            data: _items.asMap().entries.map((e) {
              final item = e.value;
              final time = '${item.time.hour}:${item.time.minute.toString().padLeft(2, '0')}:${item.time.second.toString().padLeft(2, '0')}';
              return ['${e.key + 1}', qrTypeName(item.type), item.raw, time];
            }).toList(),
          ),
          pw.SizedBox(height: 24),
          pw.Text('Generated by Cipher App', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        ],
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/cipher_batch_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      text: 'Cipher Batch Scan Report',
    );
  }

  Future<void> _exportExcel() async {
    if (_items.isEmpty) return;
    final excel = Excel.createExcel();
    final sheet = excel['Batch Scan'];

    sheet.appendRow([TextCellValue('#'), TextCellValue('Type'), TextCellValue('Data'), TextCellValue('Timestamp')]);

    for (var i = 0; i < _items.length; i++) {
      final item = _items[i];
      sheet.appendRow([
        TextCellValue('${i + 1}'),
        TextCellValue(qrTypeName(item.type)),
        TextCellValue(item.raw),
        TextCellValue(item.time.toIso8601String()),
      ]);
    }

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/cipher_batch_${DateTime.now().millisecondsSinceEpoch}.xlsx');
    await file.writeAsBytes(excel.encode()!);

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')],
      text: 'Cipher Batch Scan Data',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgDeep,
      appBar: AppBar(
        title: Text('Batch Scan', style: AppTypography.displaySm),
        leading: const BackButton(color: AppColors.textPrimary),
        actions: [
          if (_items.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.photo_library_rounded, color: AppColors.textSecondary),
              onPressed: _pickFromGallery,
              tooltip: 'Gallery',
            ),
          if (_items.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.download_rounded, color: AppColors.cyan),
              onPressed: _exportPdf,
              tooltip: 'Export PDF',
            ),
        ],
      ),
      body: SafeArea(
        child: Column(
          children: [
            // Scanner viewport
            Container(
              height: 200,
              margin: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(AppSpacing.radiusXl),
                border: Border.all(color: AppColors.glassBorder),
              ),
              clipBehavior: Clip.antiAlias,
              child: Stack(
                children: [
                  MobileScanner(controller: _scanCtrl, onDetect: _onDetect),
                  // Gallery overlay button when empty
                  if (_items.isEmpty)
                    Positioned(
                      bottom: 8,
                      right: 8,
                      child: GestureDetector(
                        onTap: _pickFromGallery,
                        child: Container(
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            color: Colors.black54,
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: const Icon(Icons.photo_library_rounded, color: Colors.white, size: 20),
                        ),
                      ),
                    ),
                ],
              ),
            ),

            // Counter & Actions
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('${_items.length} scanned', style: AppTypography.labelLg.copyWith(color: AppColors.green)),
                  Row(
                    children: [
                      _ActionChip(Icons.picture_as_pdf_rounded, 'PDF', _items.isNotEmpty ? _exportPdf : null),
                      const SizedBox(width: 8),
                      _ActionChip(Icons.table_chart_rounded, 'Excel', _items.isNotEmpty ? _exportExcel : null),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 16),

            // Items list
            Expanded(
              child: _items.isEmpty
                  ? Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Opacity(opacity: 0.2, child: Text('📋', style: TextStyle(fontSize: 48))),
                          const SizedBox(height: 12),
                          Text('No items scanned', style: AppTypography.bodyMd.copyWith(color: AppColors.textMuted)),
                          const SizedBox(height: 4),
                          Text(
                            'Point the camera at QR codes\nto batch scan them',
                            textAlign: TextAlign.center,
                            style: AppTypography.bodySm.copyWith(color: AppColors.textMuted),
                          ),
                          const SizedBox(height: 16),
                          GestureDetector(
                            onTap: _pickFromGallery,
                            child: Container(
                              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                              decoration: BoxDecoration(
                                color: AppColors.cyan.withOpacity(0.1),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: AppColors.cyan.withOpacity(0.3)),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(Icons.photo_library_rounded, size: 16, color: AppColors.cyan),
                                  const SizedBox(width: 8),
                                  Text('Pick from Gallery', style: AppTypography.labelSm.copyWith(color: AppColors.cyan)),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    )
                  : ListView.builder(
                      padding: const EdgeInsets.symmetric(horizontal: 24),
                      itemCount: _items.length,
                      itemBuilder: (_, i) {
                        final item = _items[i];
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 8),
                          child: Dismissible(
                            key: ValueKey('${item.raw}_${item.time.millisecondsSinceEpoch}'),
                            direction: DismissDirection.endToStart,
                            background: Container(
                              alignment: Alignment.centerRight,
                              padding: const EdgeInsets.only(right: 16),
                              decoration: BoxDecoration(
                                color: AppColors.red.withOpacity(0.2),
                                borderRadius: BorderRadius.circular(AppSpacing.radiusXl),
                              ),
                              child: const Icon(Icons.delete_rounded, color: AppColors.red),
                            ),
                            onDismissed: (_) => setState(() => _items.removeAt(i)),
                            child: GlassCard(
                              child: Row(
                                children: [
                                  Container(
                                    width: 3,
                                    height: 40,
                                    decoration: BoxDecoration(
                                      color: AppColors.accentFor(qrTypeName(item.type)),
                                      borderRadius: BorderRadius.circular(2),
                                    ),
                                  ),
                                  const SizedBox(width: 12),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(item.raw, style: AppTypography.bodyMd, maxLines: 1, overflow: TextOverflow.ellipsis),
                                        const SizedBox(height: 4),
                                        Text(
                                          '${item.time.hour}:${item.time.minute.toString().padLeft(2, '0')}:${item.time.second.toString().padLeft(2, '0')}',
                                          style: AppTypography.labelSm,
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  TypeBadge(type: qrTypeName(item.type)),
                                ],
                              ),
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}

class _BatchItem {
  final String raw;
  final QRType type;
  final DateTime time;
  const _BatchItem({required this.raw, required this.type, required this.time});
}

class _ActionChip extends StatelessWidget {
  const _ActionChip(this.icon, this.label, this.onTap);
  final IconData icon;
  final String label;
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedOpacity(
        opacity: onTap != null ? 1.0 : 0.4,
        duration: const Duration(milliseconds: 200),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
          decoration: BoxDecoration(
            color: AppColors.glassFill,
            borderRadius: BorderRadius.circular(AppSpacing.radiusFull),
            border: Border.all(color: AppColors.glassBorder),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 14, color: AppColors.cyan),
              const SizedBox(width: 6),
              Text(label, style: AppTypography.labelSm.copyWith(color: AppColors.textPrimary)),
            ],
          ),
        ),
      ),
    );
  }
}
