import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

class SharingService {
  /// Generates a PDF for a QR code and shares it via system sheet (Mail, WhatsApp, etc.)
  static Future<void> shareQrPdf({
    required String title,
    required String subtitle,
    required Uint8List qrImageBytes,
    String? email,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Center(
            child: pw.Column(
              mainAxisAlignment: pw.MainAxisAlignment.center,
              children: [
                pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.Text(subtitle, style: pw.TextStyle(fontSize: 14)),
                pw.SizedBox(height: 40),
                // Only show image if bytes are not empty
                if (qrImageBytes.isNotEmpty)
                  pw.Image(pw.MemoryImage(qrImageBytes), width: 300, height: 300)
                else
                  pw.Container(width: 300, height: 300, decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey))),
                pw.SizedBox(height: 40),
                pw.Text('Generated by Cipher App', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
              ],
            ),
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/cipher_export_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());

    // Share it
    final xFile = XFile(file.path, mimeType: 'application/pdf');
    await Share.shareXFiles(
      [xFile],
      text: 'Here is your generated QR from Cipher.',
      subject: title,
    );
  }

  /// Just share the raw QR image
  static Future<void> shareImage(Uint8List bytes, String title) async {
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/qr_code.png");
    await file.writeAsBytes(bytes);
    
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'image/png')],
      text: 'Scan this QR code!',
    );
  }
}
