import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_typography.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/widgets/glass_card.dart';
import '../../core/widgets/type_badge.dart';
import '../../core/services/history_service.dart';

class HistoryScreen extends StatefulWidget {
  const HistoryScreen({super.key});
  @override
  State<HistoryScreen> createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> {
  List<Map<String, dynamic>> _items = [];

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  void _loadHistory() {
    setState(() {
      _items = HistoryService.getAll();
    });
  }

  Future<void> _exportPdf() async {
    if (_items.isEmpty) return;
    final pdf = pw.Document();
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (ctx) => [
          pw.Header(
            text: 'Cipher — Scan History',
            level: 0,
            textStyle: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Text('${_items.length} scans recorded', style: const pw.TextStyle(fontSize: 12)),
          pw.SizedBox(height: 16),
          pw.Table.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            cellStyle: const pw.TextStyle(fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellPadding: const pw.EdgeInsets.all(6),
            headers: ['#', 'Type', 'Data', 'Timestamp'],
            data: _items.asMap().entries.map((e) {
              final item = e.value;
              return ['${e.key + 1}', item['type'] ?? '', item['data'] ?? '', _formatTimestamp(item['timestamp'])];
            }).toList(),
          ),
          pw.SizedBox(height: 24),
          pw.Text('Generated by Cipher App', style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        ],
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/cipher_history_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      text: 'Cipher Scan History',
    );
  }

  String _formatTimestamp(String? ts) {
    if (ts == null) return '';
    try {
      final dt = DateTime.parse(ts);
      return '${dt.day}/${dt.month} ${dt.hour}:${dt.minute.toString().padLeft(2, '0')}';
    } catch (_) {
      return ts;
    }
  }

  String _formatTime(String? ts) {
    if (ts == null) return '';
    try {
      final dt = DateTime.parse(ts);
      final now = DateTime.now();
      final diff = now.difference(dt);
      if (diff.inMinutes < 1) return 'Just now';
      if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
      if (diff.inHours < 24) return '${diff.inHours}h ago';
      return '${dt.day}/${dt.month} ${dt.hour}:${dt.minute.toString().padLeft(2, '0')}';
    } catch (_) {
      return ts ?? '';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgDeep,
      body: SafeArea(
        bottom: false,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(24, 24, 24, 20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('History', style: AppTypography.displayLg),
                      if (_items.isNotEmpty)
                        Text('${_items.length} scans', style: AppTypography.bodySm.copyWith(color: AppColors.textMuted)),
                    ],
                  ),
                  Row(
                    children: [
                      if (_items.isNotEmpty)
                        IconButton(
                          icon: const Icon(Icons.download_rounded, color: AppColors.cyan),
                          onPressed: _exportPdf,
                          tooltip: 'Export PDF',
                        ),
                      if (_items.isNotEmpty)
                        IconButton(
                          icon: const Icon(Icons.delete_outline_rounded, color: AppColors.red),
                          onPressed: () => _showClearDialog(),
                          tooltip: 'Clear All',
                        ),
                    ],
                  ),
                ],
              ),
            ),

            // Content
            Expanded(
              child: _items.isEmpty
                  ? _EmptyState()
                  : ListView.builder(
                      padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
                      itemCount: _items.length,
                      itemBuilder: (_, i) {
                        final item = _items[i];
                        final data = item['data'] as String? ?? '';
                        final type = item['type'] as String? ?? 'Text';
                        final ts = item['timestamp'] as String?;

                        return Padding(
                          padding: const EdgeInsets.only(bottom: 8),
                          child: Dismissible(
                            key: ValueKey('${data}_$ts'),
                            direction: DismissDirection.endToStart,
                            background: Container(
                              alignment: Alignment.centerRight,
                              padding: const EdgeInsets.only(right: 16),
                              decoration: BoxDecoration(
                                color: AppColors.red.withOpacity(0.15),
                                borderRadius: BorderRadius.circular(AppSpacing.radiusXl),
                              ),
                              child: const Icon(Icons.delete_rounded, color: AppColors.red),
                            ),
                            onDismissed: (_) {
                              // Hive index is reversed since we display newest first
                              final hiveIndex = HistoryService.count - 1 - i;
                              if (hiveIndex >= 0) HistoryService.deleteAt(hiveIndex);
                              _loadHistory();
                            },
                            child: GlassCard(
                              onTap: () {
                                Clipboard.setData(ClipboardData(text: data));
                                HapticFeedback.lightImpact();
                                ScaffoldMessenger.of(context).showSnackBar(
                                  SnackBar(
                                    content: const Text('Copied to clipboard'),
                                    backgroundColor: AppColors.bgElevated,
                                    behavior: SnackBarBehavior.floating,
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                    duration: const Duration(seconds: 1),
                                  ),
                                );
                              },
                              child: Row(
                                children: [
                                  Container(
                                    width: 3,
                                    height: 40,
                                    decoration: BoxDecoration(
                                      color: AppColors.accentFor(type),
                                      borderRadius: BorderRadius.circular(2),
                                    ),
                                  ),
                                  const SizedBox(width: 12),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Text(data, style: AppTypography.bodyMd, maxLines: 1, overflow: TextOverflow.ellipsis),
                                        const SizedBox(height: 4),
                                        Text(_formatTime(ts), style: AppTypography.labelSm),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 8),
                                  TypeBadge(type: type),
                                ],
                              ),
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }

  void _showClearDialog() {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: AppColors.bgElevated,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Text('Clear History?', style: AppTypography.displaySm),
        content: Text(
          'This will delete all ${_items.length} scan records. This cannot be undone.',
          style: AppTypography.bodySm,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: Text('Cancel', style: TextStyle(color: AppColors.textMuted)),
          ),
          TextButton(
            onPressed: () {
              Navigator.pop(ctx);
              HistoryService.clearAll();
              _loadHistory();
            },
            child: Text('Clear All', style: TextStyle(color: AppColors.red)),
          ),
        ],
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.qr_code_2_rounded, size: 56, color: Colors.white.withOpacity(0.06)),
            const SizedBox(height: 20),
            Text('No history yet', style: AppTypography.displaySm.copyWith(color: AppColors.textMuted)),
            const SizedBox(height: 8),
            Text(
              'Your scan history will appear here.\nStart by scanning a QR code.',
              textAlign: TextAlign.center,
              style: AppTypography.bodySm.copyWith(
                color: AppColors.textMuted,
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
