const List<String> cipherQuotes = [
  'Every QR is a door. You hold the key.',
  'In data we trust. In Cipher we encode.',
  'The code is the map. Scan the territory.',
  'Behind every QR, a world waiting to be read.',
  'Encrypt the ordinary. Decode the extraordinary.',
  'One scan away from discovery.',
  'Pixel by pixel, the truth reveals itself.',
  'The signal is in the pattern.',
  'Decode once. Remember forever.',
  'In a world of noise, be the signal.',
  'Read between the squares.',
  'Your camera is your compass.',
  'Information, compressed. Curiosity, unleashed.',
  'Every scan tells a story.',
  'From chaos to clarity, one square at a time.',
  'The best secrets hide in plain sight.',
  'Access granted. Always.',
  'Built different. Scanned better.',
  'Where data meets design.',
  'Trust the pattern. Read the code.',
  'Small square. Big possibilities.',
  'The future is scannable.',
  'Not all codes need breaking. Some just need reading.',
  'Simplicity is the ultimate sophistication.',
  'Scan. Decode. Transform.',
  'The bridge between physical and digital.',
  'Intelligence, encoded.',
  'Your gateway to the grid.',
  'Patterns speak louder than words.',
  'Unlock the unseen.',
];
